name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      # Temporarily print the token for testing purposes
      - run: echo ${{ secrets.NPM_TOKEN }}

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      # Output the npm logs if the publish step fails
      - run: cat /home/runner/.npm/_logs/*.log
