name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@WebNaresh"
      - run: npm ci
      - run: npm publish

      # Output the npm logs if the publish step fails
      - run: cat /home/runner/.npm/_logs/*.log
